{% set version = "24.04.0" %}
{% set number = 1 %}

package:
  name: mathdx
  version: {{ version }}

source:
  - url: https://files.pythonhosted.org/packages/py3/n/nvidia-mathdx/nvidia_mathdx-24.4.0-py3-none-any.whl
    sha256: 5be02c90487816c9e4f5aceb13f1466edb7e2c86608bf04eec5079e148667179

build:
  number: {{ number }}
  skip: true  # [not (linux64 or aarch64)]
  script:
    - mkdir -p $PREFIX/include/mathdx  # [linux]
    - cp -r $SRC_DIR/nvidia/mathdx/include/* $PREFIX/include/mathdx  # [linux]
    - cp $SRC_DIR/nvidia_mathdx-*.dist-info/LICENSE.txt $SRC_DIR/  # [linux]
    # copy activate/deactivate scripts
    # TODO: remove me once nvmath-python fixes the mathdx detection
    - mkdir -p "${PREFIX}/etc/conda/activate.d"                                                 # [linux]
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/mathdx_activate.sh"        # [linux]
    - mkdir -p "${PREFIX}/etc/conda/deactivate.d"                                               # [linux]
    - cp "${RECIPE_DIR}/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/mathdx_deactivate.sh"  # [linux]
    
requirements:
  build:
  host:
    - cutlass 3.3.0
  run:
    - {{ pin_compatible("cutlass", max_pin="x.x") }}
  run_constrained:
    - cuda-version >=11.0.*,<13.a0  # mathdx supports both CUDA majors

test:
  requires:
    - tree  # [linux]
  commands:
    - tree $PREFIX/include/mathdx  # [linux]
    - echo $MATHDX_HOME            # [linux]


about:
  home: https://developer.nvidia.com/mathdx
  license: LicenseRef-MathDx-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cufftdx/license.html
  license_file: LICENSE.txt
  summary: "NVIDIA MathDx device libraries"
  description: |
    NVIDIA MathDx currently contains cuFFTDx and cuBLASDx.
  doc_url: https://docs.nvidia.com/cuda/cufftdx/

extra:
  recipe-maintainers:
    - leofang
